apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-service-app
  labels:
    app: time-service-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: time-service-app
  template:
    metadata:
      labels:
        app: time-service-app
    spec:
      containers:
        - name: time-service-app
          image: 045122909431.dkr.ecr.ap-southeast-2.amazonaws.com/cns-repo:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: time-service-app-service
spec:
  selector:
    app: time-service-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

